### ISSUE TITLE
Add travis CI

### ISSUE THREAD

**Issue by andre-richter** [rust-embedded/cortex-a#3]

**Comment by berkus** [comment]
I've a working build configuration for GitHub Actions, would that work instead of Travis?

See for example [here](https://github.com/metta-systems/vesper/pull/15#event-3849829128).

**Comment by berkus** [comment]
Current implementation runs the following:
- Cargo formatting check
- Clippy check for all target platforms
- Cargo build for all target platforms on 3 host platforms (win/lin/mac)

Does NOT currently:
- Run `cargo test`, since it requires either aarch64 host or setting up QEMU and test-runner configuration. I have QEMU config in the [example above](https://github.com/metta-systems/vesper/pull/15#event-3849829128) but I did not port it over (yet).
