### ISSUE TITLE
Re-release under new name. Brainstorming.

### ISSUE THREAD

**Issue by andre-richter** [rust-embedded/cortex-a#51]
The name of this crate is not very fitting, I would like to change that.

I want to explore re-releasing this crate and want to brainstorm a better name. For quite some time it has been clear that the crate covers mainly AArch64 **CPU register access wrappers** and **wrappers for trivial assembly snippets** containing single or a few machine instructions such as barriers or control flow instructions. And I think that is a good scope that keep.
AArch32 is explicitly intended to play no role so mustn't be considered for the new crate's name.

I am currently thinking about `aarch64-cpu`. Any objections to that?

Adding a few users and contributors to get feedback: @berkus @javier-varez @vbe0201  @raw-bin

**Comment by raw-bin** [comment]
Hi.

+1 for aarch64-cpu. 

I think it's way more precise:

- The use of 'cortex' in the existing name is misleading given that 'cortex' is basically a brand and the crate is also usable for other AArch64 capable brands like Neoverse.
- The use of 'cortex-a' is misleading given that the crate is also usable for other AArch64 specific lines like Cortex-X.
- 'cortex-a' has always kept us open to the wrong impression that we also support AArch32.

**Comment by Javier-varez** [comment]
I also think `aarch64-cpu` is a much better choice than `cortex-a`. And possibly also more generic and accurate than referencing an specific architecture like armv8-a, which includes aarch32 as well, and leaves out other architectures that make use of the aarch64 execution state.

Since the crate is mainly focused towards register access, I also thought about `aarch64-regs`, but I think `aarch64-cpu` is still a better choice that also covers the asm wrappers.

**Comment by andre-richter** [comment]
Thanks!

I will try to release version 9.0.0 of this crate as aarch64-cpu later tonight 👍

**Comment by andre-richter** [comment]
Closing. This crate has been renamed and moved to https://github.com/rust-embedded/aarch64-cpu
